---
includes:
- test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
- ./config/environment
matcher:
  subjects:
  - Ordering*
  - Orders*
  - Payments*
  - PaymentProcess#call
  - PaymentProcess#release_payment
  - Pricing*
  ignore:
  - Ordering::NumberGenerator*
  - Payments::Payment#authorized?
  - Pricing::SetPriceHandler#call
  - Pricing::Configuration*
  - Pricing::SetPercentageDiscountHandler*
