---
includes:
- test
integration: minitest
requires:
- ./config/environment
matcher:
  subjects:
  - Ordering*
  - Payments*
  ignore:
  - Ordering::Order#submit
  - Ordering::NumberGenerator#call
  - Payments::Payment#authorized?
