---
includes:
- test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
- ./config/environment
matcher:
  subjects:
  - Ordering*
  - Payments*
  - Orders::OrderLine*
  - PaymentProcess#call
  ignore:
  - Ordering::NumberGenerator*
  - Payments::Payment#authorized?
