requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - ProductCatalog*
  ignore:
    - ProductCatalog::Product*
    - ProductCatalog::AssignPriceToProduct*
    - ProductCatalog::Configuration#initialize
    - ProductCatalog::Test*
