requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - ProductCatalog*
  ignore:
    - ProductCatalog::Product#register
    - ProductCatalog::Product#to_h
    - ProductCatalog::AssignPriceToProduct*
    - ProductCatalog::Test*
