---
includes:
  - test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
  - ./config/environment
matcher:
  subjects:
    - Orders*
  ignore:
    - Orders::Configuration#call
    - Orders::Configuration#change_product_price
