requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Crm*
  ignore:
    - Crm::Test*
    - Crm::Registration#initialize
    - Crm::CustomerRepositoryExamples*
    - Crm::Customer#to_h
    - Crm::Customer#register
