---
includes:
- test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
- ../../rails_application/config/environment
matcher:
  subjects:
  - Pricing*
  ignore:
  - Pricing::SetPriceHandler#call
  - Pricing::Configuration*
  - Pricing::OnCalculateTotalValue#last_discount_order_event
  - Pricing::SetPercentageDiscountHandler#last_event
