default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgres://postgres:secret@localhost/cqrs-es-sample-with-res"

test:
  <<: *default
  adapter: sqlite3
  database: ":memory:"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
