default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgres://postgres:secret@localhost/cqrs-es-sample-with-res_development"

test:
  <<: *default
  url: "postgres://postgres:secret@localhost/cqrs-es-sample-with-res_test"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
